In [4]:
#Anurag Choudhury
#202318059
import re
import csv
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup

In [3]:
#Task A

def blockmultiply(A,B,block_size):
    result = np.zeros((A.shape[0],B.shape[1]))
    for i in range(0,A.shape[0],block_size):
        for j in range(0,B.shape[1],block_size):
            for k in range(0, A.shape[1],block_size):
                result[i:i+block_size,j:j+block_size]+=np.dot(A[i:i+block_size,k:k+block_size],B[k:k+block_size,j:j+block_size])
    return result
A = np.array([[1,2,3,4,6,7,8,3], [5,6,7,8,6,5,7,8],[9,10,11,12,6,7,8,5],[13,14,15,16,5,6,7,2],[9,8,6,7,5,4,3,2],[8,9,3,5,5,6,7,3],[3,4,5,2,1,1,2,3],[5,4,3,7,6,9,0,0]])
B = np.array([[16,15,14,13,10,10,20,0],[12,11,10,9,7,7,6,6],[8,7,6,5,5,5,6,6],[4,3,2,1,7,7,7,7],[5,6,7,8,10,10,10,10],[12,11,10,9,0,0,9,0],[1,2,3,4,5,5,6,6],[7,8,9,6,9,0,8,0]])
block_size = 4
result=blockmultiply(A,B,block_size)
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResultant Matrix:")
print(result)

Matrix A:
[[ 1  2  3  4  6  7  8  3]
 [ 5  6  7  8  6  5  7  8]
 [ 9 10 11 12  6  7  8  5]
 [13 14 15 16  5  6  7  2]
 [ 9  8  6  7  5  4  3  2]
 [ 8  9  3  5  5  6  7  3]
 [ 3  4  5  2  1  1  2  3]
 [ 5  4  3  7  6  9  0  0]]

Matrix B:
[[16 15 14 13 10 10 20  0]
 [12 11 10  9  7  7  6  6]
 [ 8  7  6  5  5  5  6  6]
 [ 4  3  2  1  7  7  7  7]
 [ 5  6  7  8 10 10 10 10]
 [12 11 10  9  0  0  9  0]
 [ 1  2  3  4  5  5  6  6]
 [ 7  8  9  6  9  0  8  0]]

Resultant Matrix:
[[223. 223. 223. 211. 194. 167. 273. 166.]
 [393. 383. 373. 331. 350. 278. 445. 236.]
 [557. 527. 497. 447. 444. 399. 601. 318.]
 [678. 628. 578. 520. 518. 500. 708. 378.]
 [406. 382. 358. 326. 308. 290. 433. 201.]
 [405. 389. 373. 345. 305. 278. 437. 199.]
 [184. 175. 166. 145. 144. 117. 183.  90.]
 [318. 296. 274. 252. 202. 202. 332. 151.]]


In [8]:
#Task B
url_main = "https://open-weather13.p.rapidapi.com/city/"

cities = ["ahmedabad", "mumbai", "bangalore"]

headers = {
	"X-RapidAPI-Key": "fdb1ff3c85mshdcb6213004beb5cp1e19a5jsndc8fc8fa74a3",
	"X-RapidAPI-Host": "open-weather13.p.rapidapi.com"
}

for city in cities:
    url = url_main + city
    response = requests.get(url, headers=headers)
    print("City:", city.capitalize())
    print("Weather:", response.json()["weather"][0]["description"].capitalize())
    print("Temp:", response.json()["main"]["temp"], "\n")

City: Ahmedabad
Weather: Smoke
Temp: 69.84 

City: Mumbai
Weather: Smoke
Temp: 76.98 

City: Bangalore
Weather: Broken clouds
Temp: 75.92 



In [26]:
#Task C
from bs4 import BeautifulSoup
import requests


for n in range(1, 10):
    url = "https://www.amazon.in/s?k=iPhone"

    response = requests.get(url)
    if (response.status_code == 200):
        print("OK", n)
        soup = BeautifulSoup(response.text, "html.parser")
        data = []
        for product in soup.find_all(string = re.compile("iPhone")):
            title = product.text.strip()
            print(title)
            data.append([title])
        with open("amazon.csv", "a", encoding = "utf-8") as csvfile:
                csvwriter = csv.writer(csvfile)
                csvwriter.writerows(data)

OK 2




"iPhone"
Apple iPhone 13 (128GB) - Starlight
Apple iPhone 14 (256 GB) - (Product) RED
Apple iPhone 15 Pro (512 GB) - White Titanium
Apple iPhone 15 Pro (256 GB) - Natural Titanium
Apple iPhone 13 (128GB) - Blue
Apple iPhone 15 Plus (128 GB) - Black
6 (64GB Storage, 1GB RAM, Gold) Original Smartphone Compatible with Apple iPhone
Apple iPhone 15 Plus (256 GB) - Blue
Apple iPhone 15 Pro Max (256 GB) - Blue Titanium
Apple iPhone 13 (128GB) - Midnight
Apple iPhone 15 Plus (128 GB) - Blue
Apple iPhone 15 Plus (256 GB) - Black
Apple iPhone 15 (512 GB) - Yellow
Apple iPhone 13 (256GB) - (Product) RED
Apple iPhone 15 Plus (256 GB) - Pink
Apple iPhone 15 Pro (128 GB) - Black Titanium
OK 4




"iPhone"
Apple iPhone 13 (128GB) - Starlight
Apple iPhone 14 (256 GB) - (Product) RED
Apple iPhone 15 Pro (512 GB) - White Titanium
Apple iPhone 15 Pro (256 GB) - Natural Titanium
Apple iPhone 13 (128GB) - Blue
Apple iPhone 15 Plus (128 GB) - Black
6 (64GB Storage, 1GB RAM, Gold) Original Smartphon